//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Area
    {
        public Tb_Area()
        {
            this.Tb_Client = new HashSet<Tb_Client>();
            this.Tb_Users = new HashSet<Tb_Users>();
        }
    
        public byte Id { get; set; }
        public string Area { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Tb_Client> Tb_Client { get; set; }
        public virtual ICollection<Tb_Users> Tb_Users { get; set; }
    }
}
