//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBS
{
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tb_Collect
    {
        public int CustId { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime PayDate { get; set; }
        public string PayMon { get; set; }
        public decimal PayAmt { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> AddedBy { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual Tb_Client Tb_Client { get; set; }
    }
}
