//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Type
    {
        public Tb_Type()
        {
            this.Tb_Client = new HashSet<Tb_Client>();
        }
    
        public byte Id { get; set; }
        public string Type { get; set; }
        public decimal MonAmt { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Tb_Client> Tb_Client { get; set; }
    }
}
