//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tb_Users
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public string Cell { get; set; }
        public string User { get; set; }
        [DataType(DataType.Password)]
        public string Pwd { get; set; }
        public byte AreaId { get; set; }
        public byte RoleId { get; set; }
        public bool Status { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
    
        public virtual Tb_Area Tb_Area { get; set; }
        public virtual Tb_Roles Tb_Roles { get; set; }
    }
}
