//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Paid
    {
        public int CustId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime PayDate { get; set; }
        public string PayMon { get; set; }
        public decimal PayAmt { get; set; }
        public string Remark { get; set; }
    }
}
